local STRINGS = GLOBAL.STRINGS

STRINGS.BALATRO.BUTTON_CONFIGS = "CONFIGS"
STRINGS.BALATRO.CONFIGS_TURBO = "Turbo"
STRINGS.BALATRO.CONFIGS_REPLAY = "Replay"
STRINGS.BALATRO.CONFIGS_AUTOPLAY = "Autoplay"
STRINGS.BALATRO.CONFIGS_SKIP_ENDING = "Skip ending"
STRINGS.BALATRO.CONFIGS_REVEAL_CARDS = "Reveal cards"
STRINGS.BALATRO.CONFIGS_MACROS_END_ROUND = "Macros end round"

STRINGS.BALATRO.CONFIGS_MOST_PREFERRED_TEXT = "<----- Most preferred"
STRINGS.BALATRO.CONFIGS_LEAST_PREFERRED_TEXT = "Least preferred ----->"

STRINGS.BALATRO.MACROS = {
	-- Using emojis was a pretty good idea to fit text into the bounds of buttons
	CHOOSE_JOKER = "PICK JOKER",
	KEEP_PAIRS = "KEEP PAIRS",
	KEEP_HEARTS = "KEEP 󰀍",
	KEEP_CLUBS = "KEEP 󰀋",
	KEEP_SPADES = "KEEP 󰀪",
	KEEP_KINGS = "KEEP K",
	KEEP_QUEENS = "KEEP Q",
	KEEP_FACES = "KEEP JQK",
	DISCARD_HEARTS = "DUMP 󰀍",
	DISCARD_HEARTS_AND_DIAMONDS = "DUMP 󰀍󰀧",
	DISCARD_FACES = "DUMP JQK",
	DISCARD_ALL = "DUMP ALL",
}