-- Long-run reward distribution per game for each Smart AI goal and auto reroll setting.
-- Generated by simulating full games with the Smart AI ("Normal" thinking), using the
-- AI's own calibrated predictions (checked against the actual outcomes of the same games).
local S = {}

S.REROLL_OPTIONS = {
	{ text = "0 (terrible)", data = 0 },
	{ text = "0.5 (weak)", data = 0.5 },
	{ text = "0.8 (picky)", data = 0.8 },
	{ text = "1.0 (very picky)", data = 1.0 },
}
S.DEFAULT_REROLL = 0.5

S.DATA = {
	balanced = { games = 900,
		off = { rerolls = 0.000, dist = { 0.0491, 0.1004, 0.1301, 0.5875, 0.1008, 0.0273, 0.0043, 0.0005 } },
		[0.0] = { rerolls = 0.187, dist = { 0.0175, 0.0909, 0.1146, 0.6289, 0.1127, 0.0299, 0.0049, 0.0006 } },
		[0.5] = { rerolls = 0.385, dist = { 0.0104, 0.0550, 0.1115, 0.6671, 0.1193, 0.0306, 0.0054, 0.0007 } },
		[0.8] = { rerolls = 0.867, dist = { 0.0043, 0.0295, 0.0682, 0.7187, 0.1377, 0.0343, 0.0064, 0.0009 } },
		[1.0] = { rerolls = 1.970, dist = { 0.0016, 0.0171, 0.0307, 0.7281, 0.1659, 0.0456, 0.0098, 0.0012 } },
	},
	jackpot = { games = 600,
		off = { rerolls = 0.000, dist = { 0.0537, 0.1170, 0.1224, 0.5756, 0.0989, 0.0278, 0.0036, 0.0010 } },
		[0.0] = { rerolls = 0.212, dist = { 0.0193, 0.1118, 0.1011, 0.6225, 0.1096, 0.0303, 0.0042, 0.0012 } },
		[0.5] = { rerolls = 0.500, dist = { 0.0091, 0.0719, 0.0910, 0.6771, 0.1151, 0.0297, 0.0047, 0.0014 } },
		[0.8] = { rerolls = 1.013, dist = { 0.0036, 0.0384, 0.0690, 0.7192, 0.1296, 0.0325, 0.0058, 0.0019 } },
		[1.0] = { rerolls = 2.429, dist = { 0.0028, 0.0197, 0.0312, 0.7228, 0.1699, 0.0420, 0.0085, 0.0031 } },
	},
	safe = { games = 600,
		off = { rerolls = 0.000, dist = { 0.0563, 0.1074, 0.1350, 0.5764, 0.0916, 0.0270, 0.0054, 0.0009 } },
		[0.0] = { rerolls = 0.240, dist = { 0.0193, 0.0967, 0.1150, 0.6273, 0.1045, 0.0301, 0.0060, 0.0011 } },
		[0.5] = { rerolls = 0.496, dist = { 0.0084, 0.0664, 0.1061, 0.6693, 0.1096, 0.0318, 0.0071, 0.0013 } },
		[0.8] = { rerolls = 0.961, dist = { 0.0048, 0.0369, 0.0619, 0.7240, 0.1248, 0.0370, 0.0090, 0.0016 } },
		[1.0] = { rerolls = 2.093, dist = { 0.0032, 0.0252, 0.0308, 0.7240, 0.1527, 0.0490, 0.0128, 0.0022 } },
	},
}

local function Entry(goal, reroll)
	local g = S.DATA[goal] or S.DATA.balanced
	return (reroll ~= nil and g[reroll]) or g.off
end

-- Reward distribution (8 tiers) for a goal; reroll = threshold or nil (off).
function S.Get(goal, reroll)
	return Entry(goal, reroll).dist
end

-- Average number of rerolls per played game.
function S.Rerolls(goal, reroll)
	return Entry(goal, reroll).rerolls
end

return S
